# Site settings
title: Carnatic Scores
# email:  ananthp@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Licensed under Creative Commons. Free to download, print, and share for non-commercial purposes.
baseurl: "/carnatic_scores"
url: "http://beautifulnote.com" # the base hostname & protocol for your site
twitter_username: ananth
github_username:  ananthp

# Build settings
markdown: kramdown
